name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.17
          cache-dependency-path: ./go.mod
        id: go

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
        id: node

      - name: Get current git tag
        uses: devops-actions/action-get-tag@v1.0.2
        id: tag
        with:
          strip_v: false

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh ${{steps.tag.outputs.tag}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/asuwave_${{steps.tag.outputs.tag}}_darwin_amd64.zip
            ./build/asuwave_${{steps.tag.outputs.tag}}_darwin_arm64.zip
            ./build/asuwave_${{steps.tag.outputs.tag}}_linux_amd64.zip
            ./build/asuwave_${{steps.tag.outputs.tag}}_linux_arm64.zip
            ./build/asuwave_${{steps.tag.outputs.tag}}_windows_amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
